CREATE TABLE IF NOT EXISTS FILME (
ID BIGINT NOT NULL, 
NOME VARCHAR ( 255 ) NOT NULL, 
IMAGEM_URL VARCHAR ( 255 ) NOT NULL, 
TOTAL_VOTOS BIGINT NOT NULL,
PRIMARY KEY (ID), 
UNIQUE (ID, IMAGEM_URL) 
);